server:
  port: ${PORT:0}
spring:
  application:
    name: account-service
  devtools:
    restart:
      enabled: true

eureka:
  client:
    #service-url: {{http://localhost:8010/eureka/}}
    register-with-eureka: true
    fetch-registry: false
    proxy-port: 8761
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.uuid}}


