server:
  port: 0
spring:
  application:
    name: user-service
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    password:
    username: sa
    url: jdbc:h2:mem:testdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    #service-url: {{http://localhost:8010/eureka/}}
    register-with-eureka: true
    fetch-registry: false
    proxy-port: 8761
  instance:
    hostname: localhost
    prefer-ip-address: true

gateway:
  ip: 192.168.1.5:8011

token:
  expiration_time: 1296000000
  secret: secret

login:
  url:
    path: /users/login


