server:
  port: 8011
spring:
  application:
    name: api-gateway-service
  devtools:
    restart:
      enabled: true

eureka:
  client:
    #service-url: {{http://localhost:8010/eureka/}}
    register-with-eureka: true
    #fetch-registry: false
    proxy-port: 8761
  instance:
    hostname: localhost
    prefer-ip-address: true
api:
  login:
    url:
      path: /user-service/users/login
  registration:
    url:
      path: /user-service/users
  h2console:
    url:
      path: /user-service/h2-console/**



authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer
token:
  secret: secret