spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/morykeita/chitchat
          username: yourUsername
          password: yourPassword
          clone-on-start: true
server:
  port: 8012
